### ISSUE TITLE
Demonstrate pluggable storage back-ends

### ISSUE THREAD

**Issue by ambrosejcarr** [single-cell-data/SOMA#14]
@keller-mark I've extracted [this](https://github.com/single-cell-data/matrix-api/issues/1#issuecomment-1048055893) to respond in a separate ticket because I want to keep the javascript one focused on that use case, but I think you bring up an important point. 

> I also understand that the initial goal is to focus on the TileDB backend for the API. It would also be important to demonstrate (perhaps in the secondary draft if not the initial draft) that the initial API is flexible enough to be integrated with more than one backend, for instance with "dumber" backends like HDF5 files and Zarr stores.

You've correctly identified our focus. We believe that establishing pluggable storage back-ends is a key requirement for this project to be successful. 

We will be eager to collaborate with other storage back-ends. However, we anticipate that there will be a significant number of issues to resolve before we align on an API that effectively serves the R and python single cell toolchains. We felt it would be best to work out those details before approaching storage providers. It's our intuition that when we have a stable draft of the API, it will be relatively simple to plug in different storage back-ends, and we like the idea of demonstrating value before asking help on implementation.

**Comment by johnkerl** [comment]
Circling back -- a central part of the last many months' work has centered on the separate of the abstract spec at https://github.com/single-cell-data/SOMA, and the particular implementation https://github.com/single-cell-data/TileDB-SOMA.
