### ISSUE TITLE
Add unstructured metadata for sc_dataset

### ISSUE THREAD

**Issue by ambrosejcarr** [single-cell-data/SOMA#16]
Currently, the specification grants `uns` metadata to each `sc_group`. However, Jenny Chien notes that users will want to associate metadata to complete datasets as well:  

> `title` and `schema_version` [are the two examples] that I can think of for `sc_dataset` level metadata. [...] The alternative is to have redundant key-value metadata at  sc_group, and that typically is not ideal.

**Comment by pablo-gar** [comment]
Currently we have `SOMAExperiment`, which has measurements on `.ms` encoded as `SOMAMeasurement`.

Both `SOMAExperiments` and `SOMAMeasurement` are special cases of `SOMACollection`, and while they have some reserved keys they are flexible to include any extra metadata/data that may be deemed necessary to fit data needs.

In other words the API is flexible to include the type of metadata that Ambrose is referring to.
