### ISSUE TITLE
Test matrix should include Python 3.11

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/SOMA#176]
The GHA matrix for `python-somacore.yaml` does not include 3.11.  This seems like a worthy addition...

**Comment by johnkerl** [comment]
Follow-on to #544

**Comment by ryan-williams** [comment]
Looks like this is already done, by @johnkerl in #186 ([line](https://github.com/single-cell-data/SOMA/pull/186/files#diff-450d25ee954c72f670b09d7300c7cc2de43cda856343770a22db720c336d920fR48))?

**Comment by johnkerl** [comment]
✨
