### ISSUE TITLE
`ExperimentAxisQuery._read()` and `ExperimentAxisQuery.to_anndata()` should read and export, respectively, `obsm` `varm` `obsp` and `varp`.

### ISSUE THREAD

**Issue by pablo-gar** [single-cell-data/SOMA#177]
Currently if a SOMA `Experiment` has arrays in `obsm` `varm` `obsp` and `varp` they are not read by `ExperimentAxisQuery._read()` and thus not exported by `ExperimentAxisQuery.to_anndata()`.

These arrays should be able to be exported to an AnnData via  `ExperimentAxisQuery.to_anndata()`. 

This ticket doesn't cover the inclusion of the methods `.obsm()` `obsp()` `varm` and `varp()`

**Comment by johnkerl** [comment]
@ebezzi does this include both #178 and #179?
