### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by ivirshup** [single-cell-data/SOMA#18]
What data types have to be supported here? And should this be extensible?

By data type I’m thinking of programming types, like string, int, etc. An initial set of types:

### Collection types

* n-dimensional array
* nullable array
* sparse array (csc, csr, coo)
* tables (dataframe, collection of arrays)
* ragged arrays

### Data types

* string (exactly how is complicated)
* categorical
* 8, 16, 32, 64 bit float, int, and uint
* nullable int, float, bool
* datetime?

A very easy way to go here would to just take an existing type system – like Arrow’s.

**Comment by evanbiederstedt** [comment]
> And should this be extensible?

What do you mean by "extensible" here? @is

> What data types have to be supported here? 
> By data type I’m thinking of programming types, like string, int, etc. An initial set of types:

In terms of fundamental data types, I think this is another argument for working on the C++ API actually, cf https://github.com/single-cell-data/matrix-api/issues/2. 

Python + R + JS don't have the same fundamental data types, but encoding these within something like C++ first allows for more clear translations. 

In terms of collections:

I ask myself how much correspondence there is within the current single-cell frameworks. Consider something like the compressed sparse matrix: I'm guessing the Python packages rely on the SciPy implementation or equivalent: https://github.com/single-cell-data/matrix-api/blob/main/specification.md#proposed-single-cell-python-api

R packages use `dcgMatrix` from `Matrix`: https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/dgCMatrix-class.html

So for collections, how different is the "real implementation" for these collections written in C/C++? Or do we just accept that R/Python/JS are different beasts and use the existing frameworks (an argument against using the C/C++ API for the resulting R/Python/JS libraries)?

This might be worth a deep dive.

**Comment by pablo-gar** [comment]
With the exception of nullable array and ragged arrays, everything has been implemented in `tiledbsoma`. There are no plans in the foreseeable future to dedicate resources to it.
