### ISSUE TITLE
var for obsm

### ISSUE THREAD

**Issue by joshua-d-campbell** [single-cell-data/SOMA#23]
One other small point is that feature annotations can get produced for reduced dim objects. An example is the percentage of variance for each PC in a PCA. This knowledge can be useful to keep as it is often used for selecting PCs before downstream clustering. I wasn't sure if the current `var` data.frame is only able to correspond with the feature in X or if other `var` data frames can be included that map to the features in the reduced dim objects.

**Comment by pablo-gar** [comment]
The current specification of SOMA has `obsm` defined in a `SOMAMeasurement` which is a special case of a `SOMACollection`, this provides flexibility to include any other SOMA object(s) to meet specific needs of particular data -- in this case a `var` for `obsm` 

For example the [cell census has a feature presence matrix](https://github.com/chanzuckerberg/cell-census/blob/main/docs/cell_census_schema_0.1.0.md#feature-dataset-presence-matrix--census_objcensus_dataorganismmsrnafeature_dataset_presence_matrix--somasparsendarray), of n_datasets x n_var whose data didn't fit well in neither `varp` nor `varm`, thus we created another key-value pair within the `SOMAMeasurament`

`.ms["RNA"]["feature_dataset_presence_matrix"]`.
