### ISSUE TITLE
Linking to lower-level data structures (molecule information)

### ISSUE THREAD

**Issue by ambrosejcarr** [single-cell-data/SOMA#24]
We have aligned that Matrix-API should be a "canonical intermediate format" for omics data as opposed to a format that can also absorb all potential downstream and upstream representations [^1]. 

There is interest in capturing and linking the underlying information that is used to create the aggregated (observation, feature) matrices. These data types are out of scope for storing in Matrix-API, but it would be valuable to identify the use cases for transformation of these data types into Matrix-API representations.

Use cases, with the underlying molecular information in bold: 
* In scRNA-seq, a raw data matrix describes the number of **RNA molecules** observed for each gene in each cell[^2].
* In scATAC-seq, **genomic alignments** are counted or analyzed to create "peak", "genomic bin" or "gene activity score" features. The underlying data can be stored in WIG, BigWIG, or BedGraph formats[^3]. 
* In spatial transcriptomics studies, **RNA molecules** are spatially localized in euclidean space and assigned to cells by a segmentation algorithm. OME/ngff are exploring how to represent these data: https://github.com/ome/ngff/pull/64 and Nanostring are developing the CosMX assay which will generate this kind of information at large scale.  

[^1]: [#11, see comment](https://github.com/single-cell-data/matrix-api/issues/11#issuecomment-1066529607)
[^2]: [Example 10x experiment](https://www.10xgenomics.com/resources/datasets/10-k-1-1-mixture-of-human-hek-293-t-and-mouse-nih-3-t-3-cells-3-v-3-1-chromium-x-3-1-standard-6-1-0), [Direct download link for per-molecule information](https://cf.10xgenomics.com/samples/cell-exp/6.1.0/10k_hgmm_3p_nextgem_Chromium_X/10k_hgmm_3p_nextgem_Chromium_X_molecule_info.h5). 
[^3]: [UCSC Wig format description](https://genome.ucsc.edu/goldenPath/help/wiggle.html)

**Comment by pablo-gar** [comment]
@ambrosejcarr I'm having trouble interpreting this issue. What kind of underlying molecular information are you referring to?

**Comment by pablo-gar** [comment]
The scope of SOMA as it will be in 1.0 is not explicitly defined to include any intermediary information. But the flexibility of SOMA allows users to port these information, when possible, to SOMA objects if amenable. For example a WIG file can be represented as a SOMADenseArray.
