### ISSUE TITLE
Simple context building on declarative platform config

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/SOMA#43]

**Comment by johnkerl** [comment]
I don't remember creating this issue, and I see to my horror that the description field is entirely blank.

@thetorpedodog @mlin @atolopko-czi if you have context on whether this is closed, or closeable, or a dup, please let me know.

**Comment by atolopko-czi** [comment]
No idea. :) OK with closing it.  Important needs will resurface as new issues.
