### ISSUE TITLE
Decide if integer indexing is required.

### ISSUE THREAD

**Issue by ambrosejcarr** [single-cell-data/SOMA#6]
Do we require integer indexing on X? Specification currently proposes "no", and provides for consistent label-based indexing across X/obs/var.

**Comment by bkmartinjr** [comment]
Clarifying that this question is regarding _positional indexing_, i,e, non-label based access to arrays by position.

**Comment by ivirshup** [comment]
I think positional indexing makes a lot of sense as a requirement. I'm not sure how high performance access would work without it.

**Comment by johnkerl** [comment]
Positional indexing is implemented: https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md
