### ISSUE TITLE
Repo needs description

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/SOMA#87]
This repo needs a Description (see Above box in top-right corner of main page).  May need other cleanup as well prior to 1.0....

**Comment by johnkerl** [comment]
There is a description now:
https://github.com/single-cell-data/SOMA

@aaronwolen @pablo-gar @bkmartinjr any other action required on this issue or can we close it?

**Comment by pablo-gar** [comment]
Description has been updated
